### ISSUE TITLE
Cannot Gulp Compile

### ISSUE THREAD

**Issue by ninjazero** [segovia94/frontend-starter#1]
After $npm install and $bower install, I cannot run any gulp commands. It appears to possibly be an issue with the "let" command or something to do with strict mode. See screenshot.
<img width="1054" alt="screen shot 2017-05-02 at 11 08 57 pm" src="https://cloud.githubusercontent.com/assets/10226001/25649704/973479ca-2f8c-11e7-82af-fe950e53ab01.png">

**Comment by ninjazero** [comment]
Ok, `'use strict';` needs to be added to the top of the gulpfile.js and gulp task files.

**Comment by segovia94** [comment]
Older versions of Node.js need the `use strict` but the latest version of node does not because it defaults to es6. I ran into this same issue recently with someone that was running an older version of node and had the same problem.

**Comment by ninjazero** [comment]
Ah, I see, then it's my bad for not updating node.
